pipeline {
    agent {
        dockerfile {
            dir 'vote'
        } 
    } 
    
    stages {
        stage('test') {
            when{
            changeset "**/vote/**"
          }
            steps {
                    echo "building result test" 
                    dir ('vote') {
                        sh 'python tests'
                    }
            }
        }
    }
    post {
        always {
            echo 'This pipeline is completed'
            
        }
    }
}
