pipeline {
     agent{
           docker{
               image 'maven:3.6.1-jdk-8-slim'
               args '-v $HOME/.m2:/root/.m2'
             }
          }
    stages {
        stage('build') {
            when{
            changeset "**/worker/**"
          }
            steps {
                echo "building worker app"   
                    dir ('worker') {
                        sh 'mvn compile'
                    }
            }
        }
        stage('test') {
            when{
            changeset "**/worker/**"
          }
            steps {
                    echo "building worker test" 
                    dir ('worker') {
                        sh 'mvn clean test'
                    }
            }
        }
        stage('archive') {
            when{
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                    echo "package" 
                    dir ('worker') {
                        sh 'mvn package -DskipTests'
                        archiveArtifacts artifacts: '**/target/*.jar', fingerprint:true
                    }
            }
        }
    }
    post {
        always {
            echo 'This pipeline is completed'
            
        }
    }
}
